export const EMPLOYEE_ACTIONS = {
    UPDATE_FIELD: "UPDATE_FIELD",
    REGISTER_EMPLOYEE: "REGISTER_EMPLOYEE",
    EDIT_EMPLOYEE: "EDIT_EMPLOYEE",
    UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
    DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
    SET_ERRORS: "SET_ERRORS",
    CLEAR_ERRORS: "CLEAR_ERRORS",
    EMPLOYEE_ACTIONS:"SUBMIT_EMPLOYEE",
    UPDATE_FILTER:"UPDATE_FILTER",
    SUBMIT_EMPLOYEE: "SUBMIT_EMPLOYEE"
};